# Generated by Django 2.2.20 on 2021-09-28 02:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0152_instance_node_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtPlaybook',
            fields=[
                ('jobtemplate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='main.JobTemplate')),
                ('input_text', models.TextField(blank=True, default='')),
                ('output_yaml', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ('id',),
            },
            bases=('main.jobtemplate',),
        ),
    ]
