# Generated by Django 2.2.20 on 2021-10-11 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0154_auto_20210928_0241'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='input_text',
            new_name='input_json',
        ),
        migrations.RenameField(
            model_name='jobtemplate',
            old_name='output_yaml',
            new_name='output_playbook',
        ),
        migrations.AddField(
            model_name='atplaybook',
            name='input_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atplaybook',
            name='output_yaml',
            field=models.TextField(blank=True, default=''),
        ),
    ]
