# Generated by Django 2.2.20 on 2021-10-12 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0155_auto_20211011_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobtemplate',
            name='input_json',
        ),
        migrations.RemoveField(
            model_name='jobtemplate',
            name='output_playbook',
        ),
    ]
