# Generated by Django 2.2.20 on 2021-10-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0157_auto_20211012_0035'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atplaybook',
            options={'ordering': ('id',)},
        ),
        migrations.AddField(
            model_name='atplaybook',
            name='input_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='atplaybook',
            name='output_yaml',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='input_json',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='jobtemplate',
            name='output_playbook',
            field=models.TextField(blank=True, default=''),
        ),
    ]
